### ISSUE TITLE
WSASTARTUP not yet performed in czmq

### ISSUE THREAD

**Issue by dkrikun** [zeromq/czmq#989]
This has been discussed in zeromq issues, but in czmq the things are different because zctx lifecycle is handled automagically.
The setup is as follows: libzmq-4.0.4 and czmq (master) are linked statically into `my.dll`, on Visual Studio 2012 with CRT also linked statically in each of them.
Then the application that uses `my.dll` asserts in `zsys_shutdown()` (at `signaller.cpp:134`).
From what can be seen in Visual Studio debugger the context is not destroyed twice, nor any other code touches wsa.

Any help would be appreciated.

**Comment by hintjens** [comment]
Can you get more information about what's happening in zsys_shutdown? I.e. how often is it being called, what's the full trace stack, etc.

**Comment by dkrikun** [comment]
Being called once. If `atexit()` is deactivated, all is good even
`zsys_shutdown()` is being called from `main()`. However, if it is even
called from `my.dll()` unload hook, the assert fires.
Somehow, it looks like wsacleanup is called not from within
`zsys_shutdown()`, but  i do not know how find out.

**Comment by evoskuil** [comment]
It is hazardous to statically link MSVCRT into DLLs. Given that the runtime uses "shared" state you are likely to end up with multiple copies of that state, either via a dynamically-linked version and a statically-linked version, or via multiple statically-linked versions.

The safe design is to dynamically link MSVCRT when building DLLs (and executables that dynamically link DLLs that require MSVCRT) and statically link MSVCRT when building statically-linked executables.

Yes, this does limit your options, but it works. The problem is shared/global state, which is evil. There are many cases of this in the CRT in general, not limited to MSVCRT. I'm fighting with the case of `environ` at the moment myself. As a general rule, non-`const` global state is evil.

**Comment by dkrikun** [comment]
Thank you for your answer.

Few points, though:

1. Not sure I understand how I get shared state here. As far as I know,
static linkage implies also that a private copy of the library linked in is
made. (http://siomsystems.com/mixing-visual-studio-versions)

2. You say that global state is evil but on the other hand czmq has this
global state (zctx management). Is there any difference here?

3. Could you please add an option to avoid `atexit()` being called (via
some env. var, like other options in zsys)?

**Comment by twhittock** [comment]
See also #553 - that was resolved by adding & calling zsys_shutdown explicitly.

I had another thought due to this post - I wonder if a DllMain DLL_PROCESS_DETACH handler in the CZMQ dll which called zsys_shutdown instead of registering atexit to call zsys_shutdown would help.

When I reported this issue I was linking the dynamic CRT consistently throughout my application and all dlls, so I don't think it's a CRT mismatch.

**Comment by dkrikun** [comment]
DLL_PROCESS_DETACH produced the same result as atexit for me.

**Comment by twhittock** [comment]
Oh well... Just an idea. Calling zsys_shutdown explictly in your code when you choose to exit should work, though.

**Comment by dkrikun** [comment]
I'll try, thx

**Comment by evoskuil** [comment]
@dkrikun A private copy can certainly be a problem. There is presumably a reason certain state tries to be shared across the process. Just because it's evil doesn't mean it's not the lesser evil. C isn't exactly a safe language. The repercussions of shared state are felt in mystery bugs resulting from side effects that are very difficult to isolate or predict.

**Comment by dkrikun** [comment]
@twitthock Unfortunately I cannot just call `zsys_shutdown()` in main because czmq is a private impl. of my library.

**Comment by dkrikun** [comment]
1. Is it possible to shutdown zmq *even* if wsa has been closed?
2. If not, is it really necessary to assert?

**Comment by hintjens** [comment]
The assertion in libzmq is misguided IMO.

**Comment by hintjens** [comment]
I've pushed a fix in libzmq: https://github.com/zeromq/libzmq/issues/1377

(Not tested, don't have Windows, so @dkrikun if you can test this patch that would help.)

**Comment by hintjens** [comment]
@dkrikun if you could test this fix on libzmq, that'd be cool.

**Comment by dkrikun** [comment]
I'm sorry, but I won't do programming for a while.

**Comment by maccradar** [comment]
We are still experiencing this issue, running libzmq 4.1.2, czmq 3.0.2  and zyre. I've made a simple wrapper dll for our C# partners to run zyre, but whenever we close the application importing the dll we get this assert, with or without calling zyre_stop and zyre_destroy. I've checked signaler.cpp and it seems to already include the patch you mention above.

**Comment by maccradar** [comment]
Sorry, In our case we are receiving an assertion failed at signaller.cpp:181:
180: int nbytes = ::send (w, (char*) &dummy, sizeof (dummy), 0);
181: wsa_assert (nbytes != SOCKET_ERROR);
182: zmq_assert (nbytes == sizeof (dummy));

Adding if(WSAGetLastError() != WSANOTINITIALISED) does remove the assertion failure but the zmq_assert fails...

**Comment by maccradar** [comment]
Solved by calling zsys_shutdown explicitly!

**Comment by Asmod4n** [comment]
Can this be closed?

**Comment by maccradar** [comment]
Our issue was solved by calling zsys_shutdown, but I am not sure if it's a solution for everyone.
